language: go
go:
- '1.11'
script: go run download-caddy.go $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: BdAetAgoaS1TkHN814ze1eQDiNXaAeXkVBW2bKoORB2jTPbgM1fTRQwd1B5j5728YBjHTjIoXKJNV3VuoPe41HwImzAg8n3c5SH4BNi4xkxVHpfl1/XDSWYJBoZunpUvaYCsA1D7M/z5eKuoX0eIAfYpk3hCJ22+SfYhmfchPN2EpHRbKaNb8auKwMzd9TLcIE5bJlQDO8LgQcQXe2K3o2EZ/jVja6/p1+s5sroF+kW7dtpTf1vgIip+6quRcst+0uqHWqyTIN6pQFpZ1YXSTdeINlGQdweViXOf0B6cwPxVlk82ddu0h4LdmrRMU9siSud11RZrp5gZyZ0g9mRjICJG9b7BsGcE7k/E7jC0Wr05ACfDzABzmYvaRQilT4Okm+dMIYPovgznDKFTPy/vvYtwZuFR3TzROfG5BGPWG9twNn+DESI0OKCEg+oLdEK8ONzr9hWH4J1pRkyAhtfVhX/Y0dsR9CDkez+dCQ7oh3YpQTqEqtCrqNVlPlSbtfejJ8mGyZwvHlK4h4DzF727w61DWRc3C6plaURqbAr9eaoEJm8b99jG3bmyZdoyRvCmbNl+vEb96qDy/WZhS46b4SxyeLsNuNVfBOV4LF18XLlV6AuxkE2uw9JerKH4L4QIjWshopu09KCCWEkEkKwYHrsrNRVYaj1M9ZExD3oSC8E=
  file: "*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    repo: klingtnet/caddy-release-downloader
    tags: true
    all_branches: true
